package DataBase;

// Generated 2015-7-14 14:07:08 by Hibernate Tools 3.4.0.CR1

/**
 * CompanyTable generated by hbm2java
 */
public class CompanyTable implements java.io.Serializable {
	public static final int FYEAR=1;
	public static final int EYEAR=2;
	public static final int ERROE=3;
	
	private Integer id;
	private NoLiuDongZc noLiuDongZc;
	private SuoYouZqymain suoYouZqymain;
	private YinYeLiRun yinYeLiRun;
	private File file;
	private LiuDongZiC liuDongZiC;
	private SuoYouZqy suoYouZqy;
	private YinYeShouY yinYeShouY;
	private Company company;
	private LiuDongFuZ liuDongFuZ;
	private XianJinLl xianJinLl;
	private NliuDongFuZ nliuDongFuZ;
	private int status;
	private String year;

	public CompanyTable() {
	}

	public CompanyTable(File file, Company company, int status) {
		this.file = file;
		this.company = company;
		this.status = status;
	}

	public CompanyTable(NoLiuDongZc noLiuDongZc, SuoYouZqymain suoYouZqymain,
			YinYeLiRun yinYeLiRun, File file, LiuDongZiC liuDongZiC,
			SuoYouZqy suoYouZqy, YinYeShouY yinYeShouY, Company company,
			LiuDongFuZ liuDongFuZ, XianJinLl xianJinLl,
			NliuDongFuZ nliuDongFuZ, int status, String year) {
		this.noLiuDongZc = noLiuDongZc;
		this.suoYouZqymain = suoYouZqymain;
		this.yinYeLiRun = yinYeLiRun;
		this.file = file;
		this.liuDongZiC = liuDongZiC;
		this.suoYouZqy = suoYouZqy;
		this.yinYeShouY = yinYeShouY;
		this.company = company;
		this.liuDongFuZ = liuDongFuZ;
		this.xianJinLl = xianJinLl;
		this.nliuDongFuZ = nliuDongFuZ;
		this.status = status;
		this.year = year;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public NoLiuDongZc getNoLiuDongZc() {
		return this.noLiuDongZc;
	}

	public void setNoLiuDongZc(NoLiuDongZc noLiuDongZc) {
		this.noLiuDongZc = noLiuDongZc;
	}

	public SuoYouZqymain getSuoYouZqymain() {
		return this.suoYouZqymain;
	}

	public void setSuoYouZqymain(SuoYouZqymain suoYouZqymain) {
		this.suoYouZqymain = suoYouZqymain;
	}

	public YinYeLiRun getYinYeLiRun() {
		return this.yinYeLiRun;
	}

	public void setYinYeLiRun(YinYeLiRun yinYeLiRun) {
		this.yinYeLiRun = yinYeLiRun;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public LiuDongZiC getLiuDongZiC() {
		return this.liuDongZiC;
	}

	public void setLiuDongZiC(LiuDongZiC liuDongZiC) {
		this.liuDongZiC = liuDongZiC;
	}

	public SuoYouZqy getSuoYouZqy() {
		return this.suoYouZqy;
	}

	public void setSuoYouZqy(SuoYouZqy suoYouZqy) {
		this.suoYouZqy = suoYouZqy;
	}

	public YinYeShouY getYinYeShouY() {
		return this.yinYeShouY;
	}

	public void setYinYeShouY(YinYeShouY yinYeShouY) {
		this.yinYeShouY = yinYeShouY;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public LiuDongFuZ getLiuDongFuZ() {
		return this.liuDongFuZ;
	}

	public void setLiuDongFuZ(LiuDongFuZ liuDongFuZ) {
		this.liuDongFuZ = liuDongFuZ;
	}

	public XianJinLl getXianJinLl() {
		return this.xianJinLl;
	}

	public void setXianJinLl(XianJinLl xianJinLl) {
		this.xianJinLl = xianJinLl;
	}

	public NliuDongFuZ getNliuDongFuZ() {
		return this.nliuDongFuZ;
	}

	public void setNliuDongFuZ(NliuDongFuZ nliuDongFuZ) {
		this.nliuDongFuZ = nliuDongFuZ;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

}
