package DataBase;

// Generated 2015-6-18 23:48:40 by Hibernate Tools 3.4.0.CR1

/**
 * FileTag generated by hbm2java
 */
public class FileTag implements java.io.Serializable {

	private Integer id;
	private File file;
	private Tag tag;

	public FileTag() {
	}

	public FileTag(File file, Tag tag) {
		this.file = file;
		this.tag = tag;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

}
