package DataBase;

// Generated 2015-6-24 20:13:35 by Hibernate Tools 3.4.0.CR1

/**
 * FileCompany generated by hbm2java
 */
public class FileCompany implements java.io.Serializable {

	private Integer id;
	private File file;
	private Company company;

	public FileCompany() {
	}

	public FileCompany(File file, Company company) {
		this.file = file;
		this.company = company;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

}
