package DataBase;

// Generated 2015-6-24 20:13:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private Integer id;
	private String tag;
	private Set<FileTag> fileTags = new HashSet<FileTag>(0);

	public Tag() {
	}

	public Tag(String tag) {
		this.tag = tag;
	}

	public Tag(String tag, Set<FileTag> fileTags) {
		this.tag = tag;
		this.fileTags = fileTags;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public Set<FileTag> getFileTags() {
		return this.fileTags;
	}

	public void setFileTags(Set<FileTag> fileTags) {
		this.fileTags = fileTags;
	}

}
