package DataControl;

import java.util.ArrayList;

import DataBase.CompanyTable;
/**
 * 创造表数据
 * @author liaoshichao
 *
 */
public class TableTools {
	public static final int ZCFZ = 1; // 资产负载表
	public static final int LRB = 2; // 利润表
	public static final int XJLL = 3; // 现金流量表
	public static final int SYZQYBD = 4; // 所有者权益变动
	
	/**
	 * 创建表头
	 * @param i
	 * @return
	 */
	public static ArrayList<String> getTableHead(int i) {
		ArrayList<String> item = new ArrayList<String>();
		switch(i){
		case ZCFZ:
			item.add("公司名称");
			item.add("项目");
			item.add("期末余额");
			item.add("年初余额");
			break;
		case LRB:
			item.add("公司名称");
			item.add("项目");
			item.add("期末余额");
			item.add("年初余额");
			break;
		case XJLL:
			item.add("公司名称");
			item.add("项目");
			item.add("期末余额");
			item.add("年初余额");
			break;
		case SYZQYBD:
			item.add("公司名称");
			item.add("项目");
			item.add("实收资本");
			item.add("资本公积");
			item.add("减:库存股");
			item.add("其他综合收益");
			item.add("专项储备");
			item.add("盈余公积");
			item.add("未分配利润");
			break;
			default : break;
		}
		return item;
	}
	
	public static ArrayList<ArrayList> getTableItem(CompanyTable tab,int tabletype,int tablepart){
		ArrayList<ArrayList> item=null;
		switch(tabletype+tablepart){
		case ZCFZ:
			item=getZCFZItem(tab,tablepart);
			break;
		case LRB:
			item=getLRBItem(tab,tablepart);
			break;
		case XJLL:
			item=getXJLLItem(tab,tablepart);
			break;
		case SYZQYBD:
			item=getSYZQYBDItem(tab,tablepart);
			break;
			default : break;
		}
		return item;
	}
	
	private static ArrayList<ArrayList> getZCFZItem(CompanyTable tab,int tablepart){
		ArrayList<ArrayList> item=new ArrayList<ArrayList>();
		ArrayList<String> oiten;
		int i=0;
		switch(tablepart){
		case 0:
			oiten=new ArrayList<String>();
			
			break;
		case 1:
			i=0;
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem1().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem1().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem2().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem2().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem3().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem3().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem4().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem4().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem5().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem5().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem6().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem6().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem7().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem7().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem8().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem8().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem9().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem9().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem10().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem10().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem11().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem11().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDZC[i++]);
			oiten.add(tab.getLiuDongZiC().getItem12().split(",")[0]);
			oiten.add(tab.getLiuDongZiC().getItem12().split(",")[1]);
			item.add(oiten);
			break;
		case 2:
			i=0;
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem1().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem1().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem2().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem2().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem3().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem3().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem4().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem4().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem5().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem5().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem6().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem6().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem7().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem7().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem8().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem8().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem9().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem9().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem10().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem10().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem11().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem11().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem12().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem12().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem13().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem13().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem14().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem14().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem15().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem15().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem16().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem16().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem17().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem17().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDZC[i++]);
			oiten.add(tab.getNoLiuDongZc().getItem18().split(",")[0]);
			oiten.add(tab.getNoLiuDongZc().getItem18().split(",")[1]);
			item.add(oiten);
			break;
		case 3:
			i=0;
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem1().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem1().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem2().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem2().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem3().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem3().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem4().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem4().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem5().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem5().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem6().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem6().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem7().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem7().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem8().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem8().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem9().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem9().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem10().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem10().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem11().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem11().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem12().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem12().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.LDFZ[i++]);
			oiten.add(tab.getLiuDongFuZ().getItem13().split(",")[0]);
			oiten.add(tab.getLiuDongFuZ().getItem13().split(",")[1]);
			item.add(oiten);
			break;
		case 4:
			i=0;
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDFZ[i++]);
			oiten.add(tab.getNliuDongFuZ().getItem1().split(",")[0]);
			oiten.add(tab.getNliuDongFuZ().getItem1().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDFZ[i++]);
			oiten.add(tab.getNliuDongFuZ().getItem2().split(",")[0]);
			oiten.add(tab.getNliuDongFuZ().getItem2().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDFZ[i++]);
			oiten.add(tab.getNliuDongFuZ().getItem3().split(",")[0]);
			oiten.add(tab.getNliuDongFuZ().getItem3().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDFZ[i++]);
			oiten.add(tab.getNliuDongFuZ().getItem4().split(",")[0]);
			oiten.add(tab.getNliuDongFuZ().getItem4().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDFZ[i++]);
			oiten.add(tab.getNliuDongFuZ().getItem5().split(",")[0]);
			oiten.add(tab.getNliuDongFuZ().getItem5().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDFZ[i++]);
			oiten.add(tab.getNliuDongFuZ().getItem6().split(",")[0]);
			oiten.add(tab.getNliuDongFuZ().getItem6().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDFZ[i++]);
			oiten.add(tab.getNliuDongFuZ().getItem7().split(",")[0]);
			oiten.add(tab.getNliuDongFuZ().getItem7().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.FLDFZ[i++]);
			oiten.add(tab.getNliuDongFuZ().getItem8().split(",")[0]);
			oiten.add(tab.getNliuDongFuZ().getItem8().split(",")[1]);
			item.add(oiten);
			break;
		case 5:
			i=0;
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.SYZQY[i++]);
			oiten.add(tab.getSuoYouZqy().getItem1().split(",")[0]);
			oiten.add(tab.getSuoYouZqy().getItem1().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.SYZQY[i++]);
			oiten.add(tab.getSuoYouZqy().getItem2().split(",")[0]);
			oiten.add(tab.getSuoYouZqy().getItem2().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.SYZQY[i++]);
			oiten.add(tab.getSuoYouZqy().getItem3().split(",")[0]);
			oiten.add(tab.getSuoYouZqy().getItem3().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.SYZQY[i++]);
			oiten.add(tab.getSuoYouZqy().getItem4().split(",")[0]);
			oiten.add(tab.getSuoYouZqy().getItem4().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.SYZQY[i++]);
			oiten.add(tab.getSuoYouZqy().getItem5().split(",")[0]);
			oiten.add(tab.getSuoYouZqy().getItem5().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.SYZQY[i++]);
			oiten.add(tab.getSuoYouZqy().getItem6().split(",")[0]);
			oiten.add(tab.getSuoYouZqy().getItem6().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.SYZQY[i++]);
			oiten.add(tab.getSuoYouZqy().getItem7().split(",")[0]);
			oiten.add(tab.getSuoYouZqy().getItem7().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.SYZQY[i++]);
			oiten.add(tab.getSuoYouZqy().getItem8().split(",")[0]);
			oiten.add(tab.getSuoYouZqy().getItem8().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.SYZQY[i++]);
			oiten.add(tab.getSuoYouZqy().getItem9().split(",")[0]);
			oiten.add(tab.getSuoYouZqy().getItem9().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.SYZQY[i++]);
			oiten.add(tab.getSuoYouZqy().getItem10().split(",")[0]);
			oiten.add(tab.getSuoYouZqy().getItem10().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.SYZQY[i++]);
			oiten.add(tab.getSuoYouZqy().getItem11().split(",")[0]);
			oiten.add(tab.getSuoYouZqy().getItem11().split(",")[1]);
			item.add(oiten);
			break;
			default: break;
		}
		return item;
	}
	private static ArrayList<ArrayList> getLRBItem(CompanyTable tab,int tablepart){
		ArrayList<ArrayList> item=new ArrayList<ArrayList>();
		ArrayList<String> oiten;
		int i=0;
		switch(tablepart){
		case 0:
			i=0;
			
			break;
		case 1:
			i=0;
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYSY[i++]);
			oiten.add(tab.getYinYeShouY().getItem1().split(",")[0]);
			oiten.add(tab.getYinYeShouY().getItem1().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYSY[i++]);
			oiten.add(tab.getYinYeShouY().getItem2().split(",")[0]);
			oiten.add(tab.getYinYeShouY().getItem2().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYSY[i++]);
			oiten.add(tab.getYinYeShouY().getItem3().split(",")[0]);
			oiten.add(tab.getYinYeShouY().getItem3().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYSY[i++]);
			oiten.add(tab.getYinYeShouY().getItem4().split(",")[0]);
			oiten.add(tab.getYinYeShouY().getItem4().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYSY[i++]);
			oiten.add(tab.getYinYeShouY().getItem5().split(",")[0]);
			oiten.add(tab.getYinYeShouY().getItem5().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYSY[i++]);
			oiten.add(tab.getYinYeShouY().getItem6().split(",")[0]);
			oiten.add(tab.getYinYeShouY().getItem6().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYSY[i++]);
			oiten.add(tab.getYinYeShouY().getItem7().split(",")[0]);
			oiten.add(tab.getYinYeShouY().getItem7().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYSY[i++]);
			oiten.add(tab.getYinYeShouY().getItem8().split(",")[0]);
			oiten.add(tab.getYinYeShouY().getItem8().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYSY[i++]);
			oiten.add(tab.getYinYeShouY().getItem9().split(",")[0]);
			oiten.add(tab.getYinYeShouY().getItem9().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYSY[i++]);
			oiten.add(tab.getYinYeShouY().getItem10().split(",")[0]);
			oiten.add(tab.getYinYeShouY().getItem10().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYSY[i++]);
			oiten.add(tab.getYinYeShouY().getItem11().split(",")[0]);
			oiten.add(tab.getYinYeShouY().getItem11().split(",")[1]);
			item.add(oiten);
			break;
		case 2:
			i=0;
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem1().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem1().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem2().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem2().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem3().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem3().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem4().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem4().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem5().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem5().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem6().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem6().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem7().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem7().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem8().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem8().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem9().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem9().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem10().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem10().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem11().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem11().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem12().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem12().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem13().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem13().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem14().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem14().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem15().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem15().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.YinYLR[i++]);
			oiten.add(tab.getYinYeLiRun().getItem16().split(",")[0]);
			oiten.add(tab.getYinYeLiRun().getItem16().split(",")[1]);
			item.add(oiten);
			
			break;
			default: break;
		}
		return item;
	}
	private static ArrayList<ArrayList> getXJLLItem(CompanyTable tab,int tablepart){
		ArrayList<ArrayList> item=new ArrayList<ArrayList>();
		ArrayList<String> oiten;
		int i=0;
		switch(tablepart){
		case 1:
			i=0;
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem1().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem1().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem2().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem2().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem3().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem3().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem4().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem4().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem5().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem5().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem6().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem6().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem7().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem7().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem8().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem8().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem9().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem9().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem10().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem10().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem11().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem11().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem12().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem12().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem13().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem13().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem14().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem14().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem15().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem15().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem16().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem16().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem17().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem17().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem18().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem18().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem19().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem19().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem20().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem20().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem21().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem21().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem22().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem22().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem23().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem23().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem24().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem24().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem25().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem25().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem26().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem26().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem27().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem27().split(",")[1]);
			item.add(oiten);
			oiten=new ArrayList<String>();
			oiten.add(tab.getCompany().getName());
			oiten.add(TableItem.XJLL[i++]);
			oiten.add(tab.getXianJinLl().getItem28().split(",")[0]);
			oiten.add(tab.getXianJinLl().getItem28().split(",")[1]);
			item.add(oiten);
			break;
			default: break;
		}
		return item;
	}
	private static ArrayList<ArrayList> getSYZQYBDItem(CompanyTable tab,int tablepart){
		ArrayList<ArrayList> item=new ArrayList<ArrayList>();
		switch(tablepart){
		case 0:
			
			break;
			default: break;
		}
		return item;
	}
}
